name             'delivery-truck'
maintainer       'Chef Delivery Team'
maintainer_email 'delivery-team@chef.io'
license          'All rights reserved'
description      'Delivery Build Cookbook for your cookbooks!'
long_description 'Delivery Build Cookbook for your cookbooks!'
version          '0.3.10'

supports 'ubuntu', '>= 12.04'
supports 'redhat', '>= 6.5'
supports 'centos', '>= 6.5'
